# Generated by Django 4.1.5 on 2023-09-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_user_document_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.FileField(default='default.pdf', upload_to='media/documents/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='media/images/'),
        ),
    ]
